### ISSUE TITLE
Segmentation fault when running process.exe on AWS

### ISSUE THREAD

**Issue by shakesbear** [HPCE/hpce_2014_cw5#10]
On the AWS instance, we managed to compile our OpenCL code. However, it gives us a segmentation fault when we run process.exe. We identified that the the problem is caused by the line 
```C++
cl::Platform::get(&platforms);
```
We are sure that the header and lib files are included properly. The code was able to compile and run on cygwin on our PC. Also, we definitely used the correct AMI and used the g2.2xlarge instance.
We also tried to compile and run test_opencl.cpp on the AWS instance and the same thing happened, it compiled but gave us a segmentation fault when we tried to run it. 

Could anyone else confirm this behaviour? And are there any good workarounds?

**Comment by m8pple** [comment]
Is it actually called `process.exe`, even on the linux machine? One problem might be
windows heritage leaking through, though I'm not sure how that would happen without
some sort of compiler or loader error.

If you are using the minimal OpenCL SDK used in coursework 4, you might want to
try linking against the target system libraries instead - where is your libOpenCL.a
coming from?

**Comment by farrell236** [comment]
I got this issue when running it on the doc machines, it seems the issue was cause by the incompatible prebuilt binaries (if you are using libOpenCL.a from coursework4)

instead try to link with the libraries that's already on the machine. you can find by by running `locate libopencl` in the terminal and then linking with the .a (static lib) or .so (dynamic lib)

**Comment by shakesbear** [comment]
It's not called process.exe. I am too used to windows and just forgot. :P We have linked the correct lib now and have resolved the issue. Thanks.
