### ISSUE TITLE
Different approaches based on different input sizes

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce_2014_cw5#9]
So is it perfectly reasonable to, in main switch on arbitrary thresholds based off image dimensions to execute different approaches in the filtering, because something we might wish to exploit with smaller images will just collapse with extremely large images. 

"The input will contain a stream of images, followed by an end of file. There is no upper limit on the number of images in a stream (so don't try to store them in RAM)."

So we shouldn't be trying to read an entire frame in at a time, as its currently doing, because this could be in excess of gigabytes? Instead we should read a pre-defined number of bytes to process at a time?

Realistically is there any way we can actually test and verify correctness using the maximum dimensions you've specified?

As a sidenote, when you say you'll test these on different machines, will these be all ubuntu machines that our boostrap.sh will unpack and install our code to?

**Comment by m8pple** [comment]
For the first Q, yes. Statically switching using the image dimensions is a reasonable approach.

For the second Q, again yes. The given implementation will crash on legal inputs, which ideally
yours will not. For the biggest images it is not possible to have the whole image
in RAM, though you can store enough of the image in order to process it. There was some
discussion of this in #11 

That said, the large image stuff is deliberately a stretch: I will not be surprised if lots of
implementations are not able to do the largest image size, whether they crash or just
produce the wrong output. Testing implementations is entirely possible, you just need
to get creative and think of different ways of generating reference outputs.

And regarding aws_bootstrap.sh, yes they will be ubuntu machines as well.
